language: python

branches:
  only:
    - master
    - /^\d+\.\d+\.X$/

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
    - python: pypy
      dist: trusty
    - python: pypy3.5-5.10.1
      dist: trusty

install:
  - pip install -U pip setuptools
  - pip install -U tox-travis
script:
  - tox
